[versions]
minecraft = "1.6.4"
java = "8"
forge-compile = "9.11.1.964"
forge = "9.11.1.1345"
forgegradle = "7.0.36"
renamer = "1.1.5"
gradle = "9.3.1"
mappings = "snapshot-20130918-1.6.3"
fabric-loader = "0.18.3"
legacy-fabric-api = "1.13.2+1.6.4"
yarn-build = "604"
fabric-loom = "1.16.3"
legacy-looming = "1.16-20260528.153600-1"
legacy-fabric-gradle = "9.4.0"
ornithe-loader = "0.19.5"
feather-gen2-build = "1"
raven-gen2-build = "1"
sparrow-gen2-build = "1"
nests-gen2-build = "3"
osl-gen2 = "0.21.0-alpha.36"
ornithe-loom = "1.17.20"
ploceus = "1.17.7"
ornithe-gradle = "9.5.1"
