[versions]
minecraft = "1.6.4"
java = "8"
forge-compile = "9.11.1.964"
forge = "9.11.1.1345"
forgegradle = "7.0.36"
renamer = "1.1.5"
gradle = "9.3.1"
mappings = "snapshot-20130918-1.6.3"
fabric-loader = "0.18.3"
legacy-fabric-api = "1.13.2+1.6.4"
yarn-build = "604"
fabric-loom = "1.16.3"
legacy-looming = "1.16-20260528.153600-1"
legacy-fabric-gradle = "9.4.0"
