[versions]
minecraft = "1.8.9"
java = "8"
forge = "11.15.1.2318"
forgegradle = "2.1-20211118.174922-42"
gradle = "4.10.3"
fabric-loader = "0.18.3"
legacy-fabric-api = "1.13.2+1.8.9"
yarn-build = "604"
fabric-loom = "1.16.3"
legacy-looming = "1.16-20260528.153600-1"
legacy-fabric-gradle = "9.4.0"
