[versions]
minecraft = "1.20.1"
java = "17"
fabric-loader = "0.19.3"
quilt-loader = "0.30.0"
fabric-api = "0.92.11+1.20.1"
forge = "47.4.23"
neoforge = "47.1.106"
fabric-loom = "1.17.19"
forgegradle = "6.0.54"
moddev = "2.0.144"
