[versions]
minecraft = "1.21.1"
java = "21"
fabric-loader = "0.19.3"
quilt-loader = "0.30.0"
fabric-api = "0.116.15+1.21.1"
forge = "52.1.16"
neoforge = "21.1.248"
fabric-loom = "1.17.19"
forgegradle = "6.0.54"
moddev = "2.0.144"
