modLoader="javafml"
loaderVersion="[48,)"
license="CC0-1.0"

[[mods]]
modId="jammarr"
version="${version}"
displayName="Jammarr"
logoFile="jammarr.png"
authors="stonytark_mkii"
displayTest="MATCH_VERSION"
description='''Streams a shared, synchronized Plex music queue to every player.'''

[[dependencies.jammarr]]
modId="forge"
mandatory=true
versionRange="[48.1.0,49)"
ordering="NONE"
side="BOTH"

[[dependencies.jammarr]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.20.3)"
ordering="NONE"
side="BOTH"
