modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="jammarr"
version="${version}"
displayName="Jammarr"
logoFile="jammarr.png"
authors="stonytark_mkii"
displayTest="IGNORE_SERVER_VERSION"
description='''Streams a shared, synchronized Plex music queue to every player.'''

[[dependencies.jammarr]]
modId="forge"
mandatory=true
versionRange="[47.4.23,48)"
ordering="NONE"
side="BOTH"

[[dependencies.jammarr]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
